const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('woowil', {
  navigate: (url) => ipcRenderer.send('woowil:navigate', url),
  goBack: () => ipcRenderer.send('woowil:go-back'),
  goForward: () => ipcRenderer.send('woowil:go-forward'),
  reload: () => ipcRenderer.send('woowil:reload'),
  newTab: () => ipcRenderer.send('woowil:new-tab'),
  switchTab: (id) => ipcRenderer.send('woowil:switch-tab', id),
  closeTab: (id) => ipcRenderer.send('woowil:close-tab', id),
  reopenClosedTab: () => ipcRenderer.send('woowil:reopen-closed-tab'),
  duplicateTab: (id) => ipcRenderer.send('woowil:duplicate-tab', id),
  closeOtherTabs: (id) => ipcRenderer.send('woowil:close-other-tabs', id),
  closeTabsToRight: (id) => ipcRenderer.send('woowil:close-tabs-to-right', id),
  getWorkspaces: () => ipcRenderer.send('woowil:get-workspaces'),
  switchWorkspace: (id) => ipcRenderer.send('woowil:switch-workspace', id),
  createWorkspace: (name) => ipcRenderer.send('woowil:create-workspace', name),
  renameWorkspace: (id, name) => ipcRenderer.send('woowil:rename-workspace', id, name),
  deleteWorkspace: (id) => ipcRenderer.send('woowil:delete-workspace', id),
  toggleBookmark: () => ipcRenderer.send('woowil:toggle-bookmark'),
  getProfiles: () => ipcRenderer.send('woowil:get-profiles'),
  switchProfile: (id) => ipcRenderer.send('woowil:switch-profile', id),
  unlockProfile: (id, password) => ipcRenderer.send('woowil:unlock-profile', id, password),
  deleteProfile: (id) => ipcRenderer.send('woowil:delete-profile', id),
  createProfile: (name, password) => ipcRenderer.send('woowil:create-profile', name, password),
  accountLogin: (identifier, password) => ipcRenderer.invoke('woowil:account-login', identifier, password),
  accountLogout: () => ipcRenderer.invoke('woowil:account-logout'),
  setPanelOpen: (open) => ipcRenderer.send('woowil:set-panel-open', open),
  getBookmarksBar: () => ipcRenderer.send('woowil:get-bookmarks-bar'),
  getSuggestions: (query) => ipcRenderer.invoke('woowil:get-suggestions', query),
  setOverlayOpen: (open, height) => ipcRenderer.send('woowil:set-overlay-open', open, height),
  findInPage: (text, options) => ipcRenderer.send('woowil:find-in-page', text, options),
  closeFindBar: () => ipcRenderer.send('woowil:close-find-bar'),
  respondPermission: (id, allow) => ipcRenderer.send('woowil:respond-permission', id, allow),
  respondPasswordPrompt: (action) => ipcRenderer.send('woowil:respond-password-prompt', action),
  newWindow: () => ipcRenderer.send('woowil:new-window'),
  newIncognitoWindow: () => ipcRenderer.send('woowil:new-incognito-window'),
  restartAndUpdate: () => ipcRenderer.send('woowil:restart-and-update'),
  checkForUpdates: () => ipcRenderer.send('woowil:check-for-updates'),
  dismissUpdateBanner: () => ipcRenderer.send('woowil:dismiss-update-banner'),
  onAddress: (callback) =>
    ipcRenderer.on('address', (_event, url) => callback(url)),
  onNavState: (callback) =>
    ipcRenderer.on('nav-state', (_event, state) => callback(state)),
  onTabs: (callback) =>
    ipcRenderer.on('tabs', (_event, tabs) => callback(tabs)),
  onBookmarkState: (callback) =>
    ipcRenderer.on('bookmark-state', (_event, isBookmarked) => callback(isBookmarked)),
  onProfiles: (callback) =>
    ipcRenderer.on('profiles', (_event, data) => callback(data)),
  onTheme: (callback) =>
    ipcRenderer.on('theme', (_event, theme) => callback(theme)),
  onProfilePasswordRequired: (callback) =>
    ipcRenderer.on('profile-password-required', (_event, id) => callback(id)),
  onProfilePasswordError: (callback) =>
    ipcRenderer.on('profile-password-error', (_event, id) => callback(id)),
  onBookmarksBar: (callback) =>
    ipcRenderer.on('bookmarks-bar', (_event, bookmarks) => callback(bookmarks)),
  onWorkspaces: (callback) =>
    ipcRenderer.on('workspaces', (_event, data) => callback(data)),
  onFocusAddress: (callback) =>
    ipcRenderer.on('focus-address', () => callback()),
  onFindBar: (callback) =>
    ipcRenderer.on('find-bar', (_event, open) => callback(open)),
  onFocusFind: (callback) =>
    ipcRenderer.on('focus-find', () => callback()),
  onFindResult: (callback) =>
    ipcRenderer.on('find-result', (_event, result) => callback(result)),
  onZoomChanged: (callback) =>
    ipcRenderer.on('zoom-changed', (_event, percent) => callback(percent)),
  onDownloadsBadge: (callback) =>
    ipcRenderer.on('downloads-badge', (_event, count) => callback(count)),
  onPermissionRequest: (callback) =>
    ipcRenderer.on('permission-request', (_event, data) => callback(data)),
  onPasswordPrompt: (callback) =>
    ipcRenderer.on('password-prompt', (_event, data) => callback(data)),
  onUpdateReady: (callback) =>
    ipcRenderer.on('update-ready', (_event, version) => callback(version)),
  onExtensionsPartition: (callback) =>
    ipcRenderer.on('extensions-partition', (_event, partition) => callback(partition)),
});
